### ISSUE TITLE
No es posible refrescar el mapa

### ISSUE THREAD

**Issue by UO271612** [Arquisoft/radarin_es1b#106]
No se ha dado con una solución para poder refrescar el mapa en tiempo real, por ejemplo, al crear un nuevo meet.

**Comment by UO271612** [comment]
Solventado provisionalmente en https://github.com/Arquisoft/radarin_es1b/commit/3044284e277649a93eac98dcc41d79597c0eddf7, falta probar con más usuarios

**Comment by uo269450** [comment]
85e271158387435c711f04a313b8e4c847e1623a también los meets provisionalmente. No es actualización instantánea

**Comment by UO271612** [comment]
https://github.com/Arquisoft/radarin_es1b/commit/3044284e277649a93eac98dcc41d79597c0eddf7
