### ISSUE TITLE
Revisar el punto 6 de la Documentación

### ISSUE THREAD

**Issue by UO271612** [Arquisoft/radarin_es1b#28]

**Comment by manuel-arroyo** [comment]
517269a6cf380c671f12606ea85d0045742f8618

**Comment by manuel-arroyo** [comment]
Cerrado en commit:517269a6cf380c671f12606ea85d0045742f8618

**Comment by manuel-arroyo** [comment]
Cerrado en commit: 517269a6cf380c671f12606ea85d0045742f8618
