### ISSUE TITLE
Mejorar el Diagrama MVC (7.1) y posible conversión a Diagrama de despliegue

### ISSUE THREAD

**Issue by UO271612** [Arquisoft/radarin_es1b#29]

**Comment by uo269450** [comment]
Diagrama MVC 7.1 mejorado en el commit: 
5d9bf8b31babdf95bd3d4f0b8c5a517d405a9794

**Comment by uo269450** [comment]
Añadido diagrama de despliegue en el punto 7. : 
6664a92e7668152e8cbbec82549742fd75dcda76
