### ISSUE TITLE
Documentacion apartado 3

### ISSUE THREAD

**Issue by uo269450** [Arquisoft/radarin_es1b#3]
Describir las caracterísiticas y particularidades del projecto, el contexto del modelo de negocio en el que se va a implementar el software y finalmente el contexto técnico que engloba a la aplicación

Asignada a:
-Alberti Freije Carballo
-Guillermo Astorga Manzanal

**Comment by uo269450** [comment]
Resuelto en commit: c63f8ed8f2b01381bd5425e2727c4ad9a5c0cb1e

**Comment by uo269450** [comment]
No aparece la imagen del diagrama

**Comment by uo269450** [comment]
Arreglado en el commit: 71e74862b457be34da96bb3b4c4d4cc42f68903b

**Comment by AlbertoFreije** [comment]
Falta completar el 3.2 
Arreglado en el commit: 17524793c4832155bf60eb2f676011d6c228e9ef
