### ISSUE TITLE
Lista de búsqueda de personas

### ISSUE THREAD

**Issue by uo225211** [Arquisoft/radarin_es1b#63]
cuando entramos en la sección de buscar a un amigo, se muestra inicialmente a todo el mundo, pero luego con la búsqueda ya se filtran las personas en la lista o directamente solo se muestran los resultados de la búsqueda.
A su vez ¿Cuándo buscamos lo hacemos por nombre completo o por parte del nombre?

**Comment by uo269450** [comment]
Se hace por parte del nombre pero caracteres exactos
